// <auto-generated />
namespace ContosoUDemo.Migrations.SchoolMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PersonEmail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PersonEmail));
        
        string IMigrationMetadata.Id
        {
            get { return "201602241437366_PersonEmail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
